# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CBIR_GUI.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(1053, 788)
        self.central_widget = QtWidgets.QWidget(main_window)
        self.central_widget.setObjectName("central_widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.central_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.query_panel = QtWidgets.QVBoxLayout()
        self.query_panel.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.query_panel.setObjectName("query_panel")
        self.query_images_gb = QtWidgets.QGroupBox(self.central_widget)
        self.query_images_gb.setObjectName("query_images_gb")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.query_images_gb)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.query_images_list_view = QtWidgets.QListView(self.query_images_gb)
        font = QtGui.QFont()
        # font.setPointSize(7)
        self.query_images_list_view.setFont(font)
        self.query_images_list_view.setObjectName("query_images_list_view")
        self.horizontalLayout_2.addWidget(self.query_images_list_view)
        self.query_panel.addWidget(self.query_images_gb)
        self.choose_images_btn = QtWidgets.QPushButton(self.central_widget)
        self.choose_images_btn.setObjectName("choose_images_btn")
        self.query_panel.addWidget(self.choose_images_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addLayout(self.query_panel)
        self.search_results_panel = QtWidgets.QVBoxLayout()
        self.search_results_panel.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.search_results_panel.setObjectName("search_results_panel")
        self.search_results_gb = QtWidgets.QGroupBox(self.central_widget)
        self.search_results_gb.setObjectName("search_results_gb")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.search_results_gb)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.search_results_list_view = QtWidgets.QListView(self.search_results_gb)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.search_results_list_view.setFont(font)
        self.search_results_list_view.setFlow(QtWidgets.QListView.LeftToRight)
        self.search_results_list_view.setResizeMode(QtWidgets.QListView.Adjust)
        self.search_results_list_view.setGridSize(QtCore.QSize(150, 150))
        self.search_results_list_view.setViewMode(QtWidgets.QListView.IconMode)
        self.search_results_list_view.setObjectName("search_results_list_view")
        self.horizontalLayout_3.addWidget(self.search_results_list_view)
        self.search_results_panel.addWidget(self.search_results_gb)
        self.search_form = QtWidgets.QHBoxLayout()
        self.search_form.setObjectName("search_form")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.search_form.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.central_widget)
        self.label.setObjectName("label")
        self.search_form.addWidget(self.label)
        self.n_nearest = QtWidgets.QLineEdit(self.central_widget)
        self.n_nearest.setToolTip("")
        self.n_nearest.setObjectName("n_nearest")
        self.search_form.addWidget(self.n_nearest)
        self.search_btn = QtWidgets.QPushButton(self.central_widget)
        self.search_btn.setObjectName("search_btn")
        self.search_form.addWidget(self.search_btn)
        self.search_form.setStretch(0, 15)
        self.search_results_panel.addLayout(self.search_form)
        self.search_results_panel.setStretch(0, 15)
        self.search_results_panel.setStretch(1, 1)
        self.verticalLayout.addLayout(self.search_results_panel)
        self.verticalLayout.setStretch(0, 2)
        self.verticalLayout.setStretch(1, 6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        main_window.setCentralWidget(self.central_widget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1053, 26))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("main_window", "CBIR_GUI"))
        self.query_images_gb.setTitle(_translate("main_window", "Query images"))
        self.choose_images_btn.setText(_translate("main_window", "Choose images/folder with images"))
        self.search_results_gb.setTitle(_translate("main_window", "Search results"))
        self.label.setText(_translate("main_window", "n_nearest"))
        self.n_nearest.setText(_translate("main_window", "10"))
        self.search_btn.setText(_translate("main_window", "Search"))

